import { Router } from 'express';
import { healthRoutes } from '../models/health/health.routes.js';
import tenantRoutes from "./tenant.routes.js";
import authRoutes from "../routes/AuthRoutes/auth.routes.js";
import companyRoutes from "./CompanyRoutes/company.routes.js";
import userRoutes from "./UserRoutes/user.routes.js";
import companyUserRoutes from "./CompanyUserRoutes/companyUser.routes.js";
import roleRoutes from "./RoleRoutes/role.routes.js";
import permissionRoutes from "./PermissionRoutes/permission.routes.js";
import employeeRoutes from "./EmployeeRoutes/employee.routes.js";
import clientRoutes from "./ClientRoutes/client.routes.js";
import productRoutes from "./ProductRoutes/product.routes.js";
import inventoryRoutes from "./InventoryRoutes/inventory.routes.js";
import quoteRoutes from "./QuoteRoutes/quote.routes.js";
import salesQuoteRoutes from "./SalesQuoteRoutes/salesQuote.routes.js";
import salesOrderRoutes from "./SalesOrderRoutes/salesOrder.routes.js";
import salesOrderItemRoutes from "./SalesOrderItemsRoutes/salesOrderItem.routes.js";
import purchaseRoutes from "./PurchaseRoutes/purchase.routes.js";
import customFieldRoutes from "./CustomFieldRoutes/customField.routes.js";

export const routes = Router();

routes.use("/", tenantRoutes);
routes.use('/health', healthRoutes);
routes.use('/tenant', tenantRoutes);
routes.use('/auth', authRoutes);
routes.use("/companies", companyRoutes);
routes.use("/users", userRoutes);
routes.use("/company-users", companyUserRoutes);
routes.use("/roles", roleRoutes);
routes.use("/permissions", permissionRoutes);
routes.use("/employees", employeeRoutes);
routes.use("/clients", clientRoutes);
routes.use("/products", productRoutes);
routes.use("/inventory", inventoryRoutes);
routes.use("/quotes", quoteRoutes);
routes.use("/sales-quotes", salesQuoteRoutes);
routes.use("/sales-orders", salesOrderRoutes);
routes.use("/sales-order-items", salesOrderItemRoutes);
routes.use("/purchases", purchaseRoutes);
routes.use("/custom-fields", customFieldRoutes);